name: Generar documentación
on:
  push:
jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '14.x